Cart/urls.py
from django.urls import path
from . import views
app_name = 'cart'

urlpatterns = [
 path('', views.cart_detail, name='cart_detail'),
 path('add/<int:id>/', views.cart_add, name='cart_add'),
 path('remove/<int:id>/', views.cart_remove, name='cart_remove'),
]

shopCenter/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path('',include('shop.urls',namespace='shop')),
    path('cart/', include('Cart.urls', namespace='cart')),
    path('order/',include("Orders.urls", namespace="orders")),
    path('payment/',include("payment.urls",namespace ="payment")),
    path('coupons/', include('Coupons.urls', namespace='coupons')),
]
if settings.DEBUG:
     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/index.html
{% load static %}
<!DOCTYPE html>
<html>
 <head>
 <meta charset="utf-8" />
 <title>{% block title %}Shop Center{% endblock %}</title>
 <link href="{% static "css/base.css" %}" rel="stylesheet">
 </head>
 <body>
 <div id="header">
 <a href="/" class="logo">Shop Center</a>
 </div>
 <div id="subheader">
 
 <div class="cart">
 {% with total_items=cart|length %}
 {% if total_items > 0 %}
 Your cart:
 <a href="{% url "cart:cart_detail" %}">
 {{ total_items }} item{{ total_items|pluralize }},
 ${{ cart.get_total_price }}
 </a>
 {% else %}
 Your cart is empty.
 {% endif %}
 {% endwith %}
</div>
 </div>
 <p class="price">${{ product.price }}</p>
<form action="{% url "cart:cart_add" product.id %}" method="post">
{{ cart_product_form }}
 {% csrf_token %}
 <input type="submit" value="Add to cart">
</form>
{{ product.description|linebreaks }}
 <div id="content">
 {% block content %}
 {% endblock %}
 </div>
 </body>
</html>